name: "Cloud Foundry Auto Scale"
description: "Github Action to monitor apps and scale them up or down as needed"
inputs:
  cf_api:
    description: "Target API endpoint"
    required: true
  cf_username:
    description: "Username for API authentication"
    required: true
  cf_password:
    description: "Password for API authentication"
    required: true
  cf_org:
    description: "Target organization"
    required: true
  cf_space:
    description: "Target space"
    required: true
  cf_app_name:
    description: "The name of the app to be scaled"
    required: true
  cf_app_max_threshold:
    description: "The maximum memory threshold to trigger scaling up"
    required: true
  cf_app_min_threshold:
    description: "The minimum memory threshold to trigger scaling up"
    required: true
  cf_instance_increment:
    description: "The increment used to scale app instances up or down"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
