# This is a basic workflow to demonstrate how to use this action.

name: Auto Scale

on:
  schedule:
    - cron:  '*/5 * * * *' 
      
jobs:
  scale:
   runs-on: ubuntu-latest
   
   steps:
     - uses: cloud-gov/action-auto-scale@master
       with:
        cf_api: https://api.fr.cloud.gov
        cf_username: ${{ secrets.CG_USERNAME }}
        cf_password: ${{ secrets.CG_PASSWORD }}
        cf_org: sandbox-gsa
        cf_space: mark.headd
        cf_app_name: test-nodejs
        cf_app_max_threshold: 65
        cf_app_min_threshold: 15
        cf_instance_increment: 1
